variables:
  PYTHONPATH: "${CI_PROJECT_DIR}/src"
  ECR_REPOSITORY: 598791268315.dkr.ecr.us-east-2.amazonaws.com/sample_app_src_rep-598791268315-us-east-2
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}

stages:
  - lint
  - test
  - deploy
  - trigger

lint:
  stage: lint
  image: python:3.12
  script:
    - python3 -V  # Print out python version for debugging
    - python3 -m pip install --upgrade pip
    - python3 -m pip install black
    - python3 -m black --line-length 120 --check .

test:
  stage: test
  image: python:3.12
  script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt
    - python3 -m pytest --cov=aws_src_sample --cov-report term --cov-report=xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
    - docker build -t ${ECR_REPOSITORY}:${IMAGE_TAG} .
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
    - docker push ${ECR_REPOSITORY}:${IMAGE_TAG}
    - docker tag ${ECR_REPOSITORY}:${IMAGE_TAG} ${ECR_REPOSITORY}:prod
    - docker push ${ECR_REPOSITORY}:prod
  only:
    - main

trigger:
  stage: trigger
  image: curlimages/curl:latest
  script:
    - |
      if [ -z "${IMAGE_TAG}" ]; then
        echo "Error: IMAGE_TAG is not defined. Cannot trigger infra pipeline."
        exit 1
      fi
      echo "Triggering infrastructure pipeline for main branch with IMAGE_TAG=${IMAGE_TAG}"
      curl --request POST \
           --form token="${INFRA_TRIGGER_TOKEN}" \
           --form ref="main" \
           --form "variables[IMAGE_TAG]"="${IMAGE_TAG}" \
           "https://gitlab.com/api/v4/projects/53267064/trigger/pipeline"
  only:
    - main
